### ISSUE TITLE
Don't load

### ISSUE THREAD

**Issue by ghost** [SergeyDertan/SVault#1]
When starting server, it throws this. But i have installed KotlinLib. But the server first attempts to load SVault and then KotlinLib...
```
17:19:52 [INFO ] Lade SVault v2.1
17:19:52 [ERROR] Throwing
java.lang.NoClassDefFoundError: kotlin/TypeCastException
        at java.lang.Class.getDeclaredConstructors0(Native Method)
~[?:1.8.0_212]
        at java.lang.Class.privateGetDeclaredConstructors(Class.jav
a:2671) ~[?:1.8.0_212]
        at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8
.0_212]
        at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_21
2]
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginL
oader.java:56) ~[nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.
java:95) ~[nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager
.java:272) ~[nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager
.java:132) ~[nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager
.java:124) ~[nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager
.java:120) ~[nukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:481) ~[nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastExcepti
on
        at java.net.URLClassLoader.findClass(URLClassLoader.java:38
2) ~[?:1.8.0_212]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClass
Loader.java:44) ~[nukkit.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClass
Loader.java:28) ~[nukkit.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[
?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[
?:1.8.0_212]
        ... 12 more
17:19:52 [INFO ] Stopping other threads
```

**Comment by ghost** [comment]
Only at server with only KotlinLib and SVault installed. Works on server with many plugins lol

**Comment by ghost** [comment]
Getting other error when plugin starts:
```
17:30:05 [INFO ] Enabling SVault v2.1
> Aug 11, 2019 5:30:05 PM cn.nukkit.plugin.LibraryLoader load
INFO: Load library javax.jdo-3.2.0-m11.jar done!
Aug 11, 2019 5:30:05 PM cn.nukkit.plugin.LibraryLoader load
INFO: Load library datanucleus-core-5.2.0-release.jar done!
17:30:05 [ERROR] Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: Could n
 class Sergey_Dertan.SVault.settings.Settings
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManage
nukkit.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:733) [nukkit.j
        at cn.nukkit.Server.enablePlugins(Server.java:722) [nukkit.
        at moe.berd.FDevTools.Main.onEnable(Main.java:71) [FDevTool
]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:8
r:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPlugi
117) [nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManage
nukkit.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:733) [nukkit.j
        at cn.nukkit.Server.enablePlugins(Server.java:722) [nukkit.
        at cn.nukkit.Server.<init>(Server.java:483) [nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize cla
tan.SVault.settings.Settings
        at Sergey_Dertan.SVault.main.SVaultMain.initSettings(SVault
~[?:?]
        at Sergey_Dertan.SVault.main.SVaultMain.onEnable(SVaultMain
]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:8
ar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPlugi
117) ~[nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManage
[nukkit.jar:?]
        ... 10 more
17:30:05 [INFO ] Disabling SVault v2.1
```

**Comment by SergeyDertan** [comment]
just tested with the jar from nukkit site, try downloading kotlin lib and svault again

**Comment by uselesswaifu** [comment]
I checked the plugin.yml in the jar and its missing the dependency entry. Weird!

**Comment by SergeyDertan** [comment]
Uploaded new jar with dependency to the nukkit site
