### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GoodLucky777** [SergeyDertan/SVault#4]
I have an error!
```
2020-05-08 09:17:21.667 [main] ERROR - Throwing
java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access class kotlin.collections.ArraysUtilJVM from class kotlin.collections.ArraysKt___ArraysJvmKt
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:741) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:730) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:491) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.IllegalAccessError: tried to access class kotlin.collections.ArraysUtilJVM from class kotlin.collections.ArraysKt___ArraysJvmKt
	at kotlin.collections.ArraysKt___ArraysJvmKt.asList(_ArraysJvm.kt:37) ~[?:?]
	at kotlin.text.StringsKt__StringsKt.rangesDelimitedBy$StringsKt__StringsKt(Strings.kt:1155) ~[?:?]
	at kotlin.text.StringsKt__StringsKt.rangesDelimitedBy$StringsKt__StringsKt$default(Strings.kt:1153) ~[?:?]
	at kotlin.text.StringsKt__StringsKt.splitToSequence(Strings.kt:1176) ~[?:?]
	at kotlin.text.StringsKt__StringsKt.splitToSequence$default(Strings.kt:1175) ~[?:?]
	at kotlin.text.StringsKt__StringsJVMKt.replace(StringsJVM.kt:73) ~[?:?]
	at kotlin.text.StringsKt__StringsJVMKt.replace$default(StringsJVM.kt:72) ~[?:?]
	at Sergey_Dertan.SVault.settings.SQLiteSettings.<init>(SQLiteSettings.kt:7) ~[?:?]
	at Sergey_Dertan.SVault.settings.Settings.<clinit>(Settings.kt:30) ~[?:?]
	at Sergey_Dertan.SVault.main.SVaultMain.initSettings(SVaultMain.kt:199) ~[?:?]
	at Sergey_Dertan.SVault.main.SVaultMain.onEnable(SVaultMain.kt:70) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit-1.0-SNAPSHOT.jar:?]
	... 4 more
```

**Comment by SergeyDertan** [comment]
Can`t reproduce with latest svault and kotlinlib version

**Comment by GoodLucky777** [comment]
i don't know why this error occurs, but it happen when startup

**Comment by SergeyDertan** [comment]
Do you have latest SVault and KotlinLib plugins installed?

**Comment by GoodLucky777** [comment]
Fixed. It was PlaceholderAPI bug.
